name: Build With ncc

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: build with ncc
      uses: tool3/ncc@master
      with:
        github_token: ${{ env.GH_TOKEN }}
        src: 'index.js'
        branch: main